### ISSUE TITLE
Upload value unreal

### ISSUE THREAD

**Issue by lucaliga** [zpeters/speedtest#95] opened 2016-12-27 18:09 UTC
we make many tests and both version "speed-issues" and "v1.0.3-a" show unreal upload value. We have SHDSL 8Mb but speedtest gave us bigger upload value, quite impossible:

speedtest-32-speed-issues.exe  -s 4302 --debug

github.com/zpeters/speedtest -- unofficial cli for speedtest.net
2016/12/27 18:50:01 Env Report
2016/12/27 18:50:01 -------------------------------
2016/12/27 18:50:01 [User Environment]
2016/12/27 18:50:01 Arch: 386
2016/12/27 18:50:01 OS: windows
2016/12/27 18:50:01 IP: 82.xxx.xxx.xxx
2016/12/27 18:50:01 Lat: 45.8097
2016/12/27 18:50:01 Lon: 8.9643
2016/12/27 18:50:01 ISP: Telecom Italia Business
2016/12/27 18:50:01 Config: http://c.speedtest.net/speedtest-config.php?x=KKJLD3C1q14zt1YE
2016/12/27 18:50:01 Servers: http://c.speedtest.net/speedtest-servers-static.php?x=0MACxsPHTb1777PK
2016/12/27 18:50:01 User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.21 Safari/537.36
2016/12/27 18:50:01 -------------------------------
2016/12/27 18:50:01 [args]
2016/12/27 18:50:01 []string{"speedtest-32-speed-issues.exe", "-s", "4302", "--debug"}
2016/12/27 18:50:01 --------------------------------
2016/12/27 18:50:01 Getting all servers for our test list
2016/12/27 18:50:03 Server '4302' specified, getting info...
2016/12/27 18:50:03 Testing latency: Milan (Vodafone IT)
2016/12/27 18:50:03     Run took: 31.25ms
2016/12/27 18:50:03 Testing latency: Milan (Vodafone IT)
2016/12/27 18:50:03     Run took: 31.25ms
2016/12/27 18:50:03 Testing latency: Milan (Vodafone IT)
2016/12/27 18:50:03     Run took: 31.25ms
2016/12/27 18:50:03 Testing latency: Milan (Vodafone IT)
2016/12/27 18:50:03     Run took: 31.25ms
2016/12/27 18:50:03 Testing latency: Milan (Vodafone IT)
2016/12/27 18:50:03     Run took: 46.875ms
Server: 4302 - Milan (Vodafone IT)
2016/12/27 18:50:03 Testing download speed
2016/12/27 18:50:03 Starting test at: 2016-12-27 18:50:03.46875 +0100 CET
.2016/12/27 18:50:04 Starting test at: 2016-12-27 18:50:04.15625 +0100 CET
.2016/12/27 18:50:05 Starting test at: 2016-12-27 18:50:05.453125 +0100 CET
.2016/12/27 18:50:08 Starting test at: 2016-12-27 18:50:08.328125 +0100 CET
.2016/12/27 18:50:13 Starting test at: 2016-12-27 18:50:13.390625 +0100 CET
.2016/12/27 18:50:24 Starting test at: 2016-12-27 18:50:24.734375 +0100 CET
.2016/12/27 18:50:44 Starting test at: 2016-12-27 18:50:44.828125 +0100 CET
.2016/12/27 18:51:16 Starting test at: 2016-12-27 18:51:16.484375 +0100 CET
.2016/12/27 18:52:01 Starting test at: 2016-12-27 18:52:01.75 +0100 CET
.2016/12/27 18:53:03 Starting test at: 2016-12-27 18:53:03.5625 +0100 CET
.
2016/12/27 18:55:08 Testing upload speed
2016/12/27 18:55:08 Starting test at: 2016-12-27 18:55:08.21875 +0100 CET
2016/12/27 18:55:08 Starting test at: 1482861308218750000 (nano)
2016/12/27 18:55:08 Finishing test at: 2016-12-27 18:55:08.40625 +0100 CET
2016/12/27 18:55:08 Finishing test at: 1482861308406250000 (nano)
2016/12/27 18:55:08 Took: 187500000 (nano)
.2016/12/27 18:55:08 Starting test at: 2016-12-27 18:55:08.515625 +0100 CET
2016/12/27 18:55:08 Starting test at: 1482861308515625000 (nano)
2016/12/27 18:55:08 Finishing test at: 2016-12-27 18:55:08.75 +0100 CET
2016/12/27 18:55:08 Finishing test at: 1482861308750000000 (nano)
2016/12/27 18:55:08 Took: 234375000 (nano)
.2016/12/27 18:55:08 Starting test at: 2016-12-27 18:55:08.953125 +0100 CET
2016/12/27 18:55:08 Starting test at: 1482861308953125000 (nano)
2016/12/27 18:55:09 Finishing test at: 2016-12-27 18:55:09.28125 +0100 CET
2016/12/27 18:55:09 Finishing test at: 1482861309281250000 (nano)
2016/12/27 18:55:09 Took: 328125000 (nano)
.2016/12/27 18:55:09 Starting test at: 2016-12-27 18:55:09.5 +0100 CET
2016/12/27 18:55:09 Starting test at: 1482861309500000000 (nano)
2016/12/27 18:55:09 Finishing test at: 2016-12-27 18:55:09.828125 +0100 CET
2016/12/27 18:55:09 Finishing test at: 1482861309828125000 (nano)
2016/12/27 18:55:09 Took: 328125000 (nano)
.2016/12/27 18:55:10 Starting test at: 2016-12-27 18:55:10.109375 +0100 CET
2016/12/27 18:55:10 Starting test at: 1482861310109375000 (nano)
2016/12/27 18:55:10 Finishing test at: 2016-12-27 18:55:10.4375 +0100 CET
2016/12/27 18:55:10 Finishing test at: 1482861310437500000 (nano)
2016/12/27 18:55:10 Took: 328125000 (nano)
.
Ping (Lowest): 31.25 ms | Download (Max): 3.00 Mbps | Upload (Max): **28.82 Mbps**

Thanks for help.

**Comment by zpeters** [comment] 2016-12-27 20:14
thank you for the report. could be a few days until i can look

**Comment by zpeters** [comment] 2016-12-27 22:26
Does download speed and ping seem appropriate for what you normally see?

**Comment by polyzen** [comment] 2016-12-27 23:20
Duplicate of #44?

**Comment by lucaliga** [comment] 2016-12-28 07:37
To [zpeters](https://github.com/zpeters) : all download and ping seems appropriate and similar, only some servers upload are quite wrong.
To [polyzen](https://github.com/polyzen) :  you're right is the same of https://github.com/zpeters/speedtest/issues/44 and depend on speedtest server used. Moreover I wrote wrong because very high and unreal upload are reported in version "speed-issues" and "v1.0.2-c". Instead in version "v1.0.3-a" for the same server reports very low upload.  I'm running the tool version "v1.0.2-c" every 20/30 minutes (random) since 2 days. All ping and download seems correct.  Mostly upload-speeds are correct except for one server . These are last night running result in bold the strange values.

2016-12-28 00:08:18 +0100,3667,Telecom Italia S.p.A.(Milan,Italy),31.25,3135,1303
2016-12-28 00:23:21 +0100,10402,Telecom Italia Spa(Turin,Italy),31.25,3130,1315
2016-12-28 00:40:07 +0100,10406,Telecom Italia Spa(Genoa,Italy),62.50,3125,2803
2016-12-28 00:58:16 +0100,7839,Fastweb SpA(Milan,Italy),15.63,3150,1328
2016-12-28 01:18:20 +0100,4302,Vodafone IT(Milan,Italy),31.25,3169,**268433**
2016-12-28 01:59:32 +0100,3667,Telecom Italia S.p.A.(Milan,Italy),31.25,3160,2939
2016-12-28 02:14:22 +0100,10402,Telecom Italia Spa(Turin,Italy),31.25,3177,1398
2016-12-28 02:31:05 +0100,10406,Telecom Italia Spa(Genoa,Italy),46.88,3152,1211
2016-12-28 02:49:28 +0100,7839,Fastweb SpA(Milan,Italy),31.25,3186,1474
2016-12-28 03:09:30 +0100,4302,Vodafone IT(Milan,Italy),156.25,3199,**536867**
2016-12-28 03:52:18 +0100,3667,Telecom Italia S.p.A.(Milan,Italy),46.88,3145,3061
2016-12-28 04:07:03 +0100,10402,Telecom Italia Spa(Turin,Italy),15.63,3134,2982
2016-12-28 04:23:39 +0100,10406,Telecom Italia Spa(Genoa,Italy),46.88,3138,1266
2016-12-28 04:42:06 +0100,7839,Fastweb SpA(Milan,Italy),31.25,3158,2781
2016-12-28 05:01:47 +0100,4302,Vodafone IT(Milan,Italy),31.25,3142,**536867**

Anyway if issue depends on the speedtest server being used the only resolution is to not use it or to blacklist with -b parameter. Note that using web browser http://beta.speedtest.net and selecting the same server reports correct value.

Thanks. Ciao.

**Comment by lucaliga** [comment] 2016-12-28 07:38
Sorry wrong click..not closed if anyone find other solution.

**Closed** 2016-12-28 16:40 UTC
