### ISSUE TITLE
Cannot get speedtest config

### ISSUE THREAD

**Issue by VIGOPO** [zpeters/speedtest#84] opened 2016-08-25 03:33 UTC
Good afternoon! Thank you for the utility! Use your application for Windows, downloaded the latest version!
Since yesterday began to receive the error "Can not get speedtest config" and nothing does not work, you can help the problem?

![default](https://cloud.githubusercontent.com/assets/21233083/17955847/4a166c04-6aaf-11e6-880a-f771470fea95.jpg)

**Comment by nemchik** [comment] 2016-08-25 14:32
I'm also having this issue. I tested the 1.0 release and the 1.0.2-1 release.
I had previously used the 1.0 release successfully.

**Comment by zpeters** [comment] 2016-08-25 14:36
Thank you i will try to take a look at this as soon as i can

**Comment by zpeters** [comment] 2016-08-25 15:46
it is very possible they are starting to block traffic from the app.  i need to do some more research into this.

**Comment by zpeters** [comment] 2016-08-25 15:49
Looks like they are blocking empty or certain User Agent strings.  Technically this is an easy fix, but i have to think about some of the implications

**Comment by zpeters** [comment] 2016-08-25 16:17
In a few minutes some testing code should be uploaded here.  Please let me know if this works for you.

http://media.thehelpfulhacker.net/index.php?dir=speedtest/v1.0.2-b/

**Comment by nemchik** [comment] 2016-08-25 16:54
first run returned this:

```
C:\WINDOWS\system32>C:\ktemp\speedtest-64-v1.0.2-b.exe
github.com/zpeters/speedtest -- unofficial cli for speedtest.net
2016/08/25 11:53:34 Get http://noc.vci.net/speedtest/speedtest/latency.txt: dial tcp: lookup noc.vci.net: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
```

Subsequent runs have been successful.

**Comment by zpeters** [comment] 2016-08-25 23:23
I think this is fixed now

https://github.com/zpeters/speedtest/releases/tag/v1.0.2-b

**Comment by marcelfarres** [comment] 2016-10-13 07:46
I am having a similar problem (Go 1.6.2 clean install over ubuntu 14)

```
2016/10/13 03:43:33 Cannot get speedtest config
2016/10/13 03:43:33 Get http://c.speedtest.net/speedtest-config.php?x=3gDoShJrfJMCI64c: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by zpeters** [comment] 2016-10-13 11:41
If you try again do you still see that issue?  From where you are running the command can you browse to or download (wget, curl, etc) the url it is trying to get?  http://c.speedtest.net/speedtest-config.php?x=XXXXXXXXX

**Comment by zpeters** [comment] 2016-10-13 15:09
Also please try a run with the "-d" option for additional debugging info.

**Comment by zpeters** [comment] 2016-10-13 17:07
This could be somethign in a newer library.  Finally got a chance to test on a "clean" install and i'm getting a similar issue....

**Comment by marcelfarres** [comment] 2016-10-13 17:43
The error disappear after I update & upgrade Ubuntu and I restart the server (I don't know if something else make it disappear). 

I am not able to reproduce the error again.

**Comment by zpeters** [comment] 2016-10-13 17:43
Still working on this and it appears to be with the http timeout settings..still looking at this...

**Comment by zpeters** [comment] 2016-10-13 17:53
very strange...i'm getting mixed results here depending on what servers i am checking against...nothing conclusive yet

**Comment by zpeters** [comment] 2016-10-22 21:25
Still working on this...

**Comment by zpeters** [comment] 2016-10-22 22:33
I believe some of the blacklisting issues, timeout issues and a few other things have been resolved in this development release.  Please let me know how this looks.  If everything seems stable i'll push this to the main branch next week.

https://github.com/zpeters/speedtest/releases/tag/v1.0.2-c-fixes

Thank you

**Closed** 2016-10-26 00:45 UTC
Labels: inprogress
